<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>better_lidar</name>
  <version>0.1.0</version>
  <description>GPU Lidar simulation with intensity attenuation for Gazebo Harmonic</description>
  <maintainer email="hehaoyang1124@outlook.com">何昊阳(He Haoyang)</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>gz-sim8</depend>
  <depend>gz-transport13</depend>
  <depend>gz-msgs10</depend>
  <depend>gz-common5</depend>

  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>ros2launch</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>